export const SCORING_CONSTANTS = {
  BASE_SCORE: 1000,
  MAX_TIME_BONUS: 500,
  MAX_STREAK_BONUS_MULTIPLIER: 2,
  MAX_DIFFICULTY_MULTIPLIER: 2,
  MAX_RESPONSE_TIME_MS: 20000, // 20 seconds
  MIN_RESPONSE_TIME_MS: 500, // 0.5 seconds
  STREAK_BONUS_INCREMENT: 0.1, // 10% per streak
};
