# PLAYER API

@baseUrl = http://localhost:3000

# Player Endpoints

### findAll
GET {{baseUrl}}/players

### findById
GET {{baseUrl}}/players/:id

### getCurrentRoom
GET {{baseUrl}}/players/:id/current-room

### create
POST {{baseUrl}}/players
Content-Type: application/json

{
  // Player data
  "name": "player name",
  "description": "player description"
}

### updateStatus
PUT {{baseUrl}}/players/:id/status
Content-Type: application/json

{
  // Player data
  "id": "uuid-goes-here",
  "name": "updated player name"
}

# Template CRUD Operations
# These are common operations that might not be implemented in your controller yet

### findOne (Template)
GET {{baseUrl}}/players/:id

### update (Template)
PATCH {{baseUrl}}/players/:id
Content-Type: application/json

{
  "name": "updated player name",
  "description": "updated player description"
}

### remove (Template)
DELETE {{baseUrl}}/players/:id

