# RESOURCE-MANAGER API

@baseUrl = http://localhost:3000

# Resource-manager Endpoints

### getSystemStatus
GET {{baseUrl}}/resource-manager/status

### getResourceUtilization
GET {{baseUrl}}/resource-manager/utilization

### getScalingRules
GET {{baseUrl}}/resource-manager/scaling/rules

### getScalingEvents
GET {{baseUrl}}/resource-manager/scaling/events

### getAlertConfigs
GET {{baseUrl}}/resource-manager/alerts/configs

### getRecentAlerts
GET {{baseUrl}}/resource-manager/alerts/recent

### getCostAnalysis
GET {{baseUrl}}/resource-manager/cost/analysis

### createScalingRule
POST {{baseUrl}}/resource-manager/scaling/rules
Content-Type: application/json

{
  // Resource-manager data
  "name": "resource-manager name",
  "description": "resource-manager description"
}

### updateScalingRule
POST {{baseUrl}}/resource-manager/scaling/rules/update
Content-Type: application/json

{
  // Resource-manager data
  "name": "resource-manager name",
  "description": "resource-manager description"
}

### manualScaling
POST {{baseUrl}}/resource-manager/scaling/manual
Content-Type: application/json

{
  // Resource-manager data
  "name": "resource-manager name",
  "description": "resource-manager description"
}

### createAlertConfig
POST {{baseUrl}}/resource-manager/alerts/configs
Content-Type: application/json

{
  // Resource-manager data
  "name": "resource-manager name",
  "description": "resource-manager description"
}

### updateAlertConfig
POST {{baseUrl}}/resource-manager/alerts/configs/update
Content-Type: application/json

{
  // Resource-manager data
  "name": "resource-manager name",
  "description": "resource-manager description"
}

### deleteScalingRule
DELETE {{baseUrl}}/resource-manager/scaling/rules/:id

### deleteAlertConfig
DELETE {{baseUrl}}/resource-manager/alerts/configs/:id

# Template CRUD Operations
# These are common operations that might not be implemented in your controller yet

### findAll (Template)
GET {{baseUrl}}/resource-manager

### findOne (Template)
GET {{baseUrl}}/resource-manager/:id

### create (Template)
POST {{baseUrl}}/resource-manager
Content-Type: application/json

{
  "name": "resource-manager name",
  "description": "resource-manager description"
}

### update (Template)
PATCH {{baseUrl}}/resource-manager/:id
Content-Type: application/json

{
  "name": "updated resource-manager name",
  "description": "updated resource-manager description"
}

### remove (Template)
DELETE {{baseUrl}}/resource-manager/:id

