# ROOM-MOVEMENT API

@baseUrl = http://localhost:3000

# Room-movement Endpoints

### getRoomPlayers
GET {{baseUrl}}/room-movement/room/:roomId/players

### getPlayerRoomHistory
GET {{baseUrl}}/room-movement/player/:playerId/history

### joinRoom
POST {{baseUrl}}/room-movement/join
Content-Type: application/json

{
  // Room-movement data
  "name": "room-movement name",
  "description": "room-movement description"
}

### leaveRoom
POST {{baseUrl}}/room-movement/leave
Content-Type: application/json

{
  // Room-movement data
  "name": "room-movement name",
  "description": "room-movement description"
}

# Template CRUD Operations
# These are common operations that might not be implemented in your controller yet

### findAll (Template)
GET {{baseUrl}}/room-movement

### findOne (Template)
GET {{baseUrl}}/room-movement/:id

### create (Template)
POST {{baseUrl}}/room-movement
Content-Type: application/json

{
  "name": "room-movement name",
  "description": "room-movement description"
}

### update (Template)
PATCH {{baseUrl}}/room-movement/:id
Content-Type: application/json

{
  "name": "updated room-movement name",
  "description": "updated room-movement description"
}

### remove (Template)
DELETE {{baseUrl}}/room-movement/:id

