# STORE API

@baseUrl = http://localhost:3000

# Store Endpoints

### getItems
GET {{baseUrl}}/store/items

### getInventory
GET {{baseUrl}}/store/inventory

### getTransactions
GET {{baseUrl}}/store/transactions

### purchaseItem
POST {{baseUrl}}/store/purchase
Content-Type: application/json

{
  // Store data
  "name": "store name",
  "description": "store description"
}

# Template CRUD Operations
# These are common operations that might not be implemented in your controller yet

### findAll (Template)
GET {{baseUrl}}/store

### findOne (Template)
GET {{baseUrl}}/store/:id

### create (Template)
POST {{baseUrl}}/store
Content-Type: application/json

{
  "name": "store name",
  "description": "store description"
}

### update (Template)
PATCH {{baseUrl}}/store/:id
Content-Type: application/json

{
  "name": "updated store name",
  "description": "updated store description"
}

### remove (Template)
DELETE {{baseUrl}}/store/:id

